@baseUri= users	
    

# @name registerNewUser
POST http://{{hostname}}/{{baseUri}} HTTP/1.1

{
    "first_name": "Foo",
    "last_name": "Bar",
    "dateOfBirth": "1983-01-02T15:04:05Z",
    "email": "foo@example.com",

    "phone_country_code": "+64",
    "phone_area_code": "023",
    "phone_number": "123456",

    "location_longitude": -41.26595602617756,
	"location_latitude": 173.3002574488138
}

###

# @name getUserById
GET http://{{hostname}}/{{baseUri}}/cbca0820-69e1-4e98-8d7c-9d01213d5c02 HTTP/1.1