// Code generated by MockGen. DO NOT EDIT.
// Source: registration.go
//
// Generated by this command:
//
//	mockgen -source=registration.go -destination=../mocks/registration.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistration is a mock of Registration interface.
type MockRegistration struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationMockRecorder
	isgomock struct{}
}

// MockRegistrationMockRecorder is the mock recorder for MockRegistration.
type MockRegistrationMockRecorder struct {
	mock *MockRegistration
}

// NewMockRegistration creates a new mock instance.
func NewMockRegistration(ctrl *gomock.Controller) *MockRegistration {
	mock := &MockRegistration{ctrl: ctrl}
	mock.recorder = &MockRegistrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistration) EXPECT() *MockRegistrationMockRecorder {
	return m.recorder
}

// Done mocks base method.
func (m *MockRegistration) Done() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Done")
}

// Done indicates an expected call of Done.
func (mr *MockRegistrationMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockRegistration)(nil).Done))
}

// GetRegistrationVerificationEmailData mocks base method.
func (m *MockRegistration) GetRegistrationVerificationEmailData(uid uuid.UUID) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationVerificationEmailData", uid)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationVerificationEmailData indicates an expected call of GetRegistrationVerificationEmailData.
func (mr *MockRegistrationMockRecorder) GetRegistrationVerificationEmailData(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationVerificationEmailData", reflect.TypeOf((*MockRegistration)(nil).GetRegistrationVerificationEmailData), uid)
}

// VerifyUserRegistration mocks base method.
func (m *MockRegistration) VerifyUserRegistration(ctx context.Context, uid uuid.UUID, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserRegistration", ctx, uid, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyUserRegistration indicates an expected call of VerifyUserRegistration.
func (mr *MockRegistrationMockRecorder) VerifyUserRegistration(ctx, uid, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserRegistration", reflect.TypeOf((*MockRegistration)(nil).VerifyUserRegistration), ctx, uid, hash)
}
