// Code generated by MockGen. DO NOT EDIT.
// Source: user_account.go
//
// Generated by this command:
//
//	mockgen -source=user_account.go -destination=../../mocks/user_account.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	aggregate "github.com/wizact/go-todo-api/internal/user/domain/aggregates"
	httpservermodel "github.com/wizact/go-todo-api/pkg/http-server-model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserAccountUseCase is a mock of UserAccountUseCase interface.
type MockUserAccountUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUserAccountUseCaseMockRecorder
	isgomock struct{}
}

// MockUserAccountUseCaseMockRecorder is the mock recorder for MockUserAccountUseCase.
type MockUserAccountUseCaseMockRecorder struct {
	mock *MockUserAccountUseCase
}

// NewMockUserAccountUseCase creates a new mock instance.
func NewMockUserAccountUseCase(ctrl *gomock.Controller) *MockUserAccountUseCase {
	mock := &MockUserAccountUseCase{ctrl: ctrl}
	mock.recorder = &MockUserAccountUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAccountUseCase) EXPECT() *MockUserAccountUseCaseMockRecorder {
	return m.recorder
}

// GetUserById mocks base method.
func (m *MockUserAccountUseCase) GetUserById(ctx context.Context, uid uuid.UUID) (aggregate.User, *httpservermodel.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, uid)
	ret0, _ := ret[0].(aggregate.User)
	ret1, _ := ret[1].(*httpservermodel.AppError)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockUserAccountUseCaseMockRecorder) GetUserById(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockUserAccountUseCase)(nil).GetUserById), ctx, uid)
}

// RegisterNewUser mocks base method.
func (m *MockUserAccountUseCase) RegisterNewUser(ctx context.Context, user aggregate.User) (aggregate.User, *httpservermodel.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterNewUser", ctx, user)
	ret0, _ := ret[0].(aggregate.User)
	ret1, _ := ret[1].(*httpservermodel.AppError)
	return ret0, ret1
}

// RegisterNewUser indicates an expected call of RegisterNewUser.
func (mr *MockUserAccountUseCaseMockRecorder) RegisterNewUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNewUser", reflect.TypeOf((*MockUserAccountUseCase)(nil).RegisterNewUser), ctx, user)
}

// UpdateUser mocks base method.
func (m *MockUserAccountUseCase) UpdateUser(ctx context.Context, user aggregate.User) (aggregate.User, *httpservermodel.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(aggregate.User)
	ret1, _ := ret[1].(*httpservermodel.AppError)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserAccountUseCaseMockRecorder) UpdateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserAccountUseCase)(nil).UpdateUser), ctx, user)
}
